language: node_js
node_js:
- '6'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- npm install hexo-cli -g
- npm install
- hexo clean && hexo g
before_install:
- openssl aes-256-cbc -K $encrypted_b72a4d12824d_key -iv $encrypted_b72a4d12824d_iv
  -in travis_key.enc -out travis_key -d
before_script:
- echo -e "Host 2mih.com\n\tStrictHostKeyChecking no\n" >> ~\/.ssh\/config
script:
- chmod 600 travis_key
- scp -r -i travis_key .\/public travis@2mih.com:\/home\/travis\/
