language: node_js
node_js:
- '6'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: 2mih.com
install:
- npm install hexo-cli -g
- npm install
- hexo clean && hexo g
before_install:
- openssl aes-256-cbc -K $encrypted_b72a4d12824d_key -iv $encrypted_b72a4d12824d_iv
  -in travis_key.enc -out travis_key -d
script:
- bash deploy.sh
